kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang:1.21
  detach: true
  commands:
  - echo "===> Go Version"
  - go version
  - echo "===> Go Proxy"
  - go env -w GOPROXY=https://mirrors.aliyun.com/goproxy/,direct
  - echo "===> Go Env Info"
  - go env

  - echo "===> Docker"
  - docker images
  - docker ps

  - echo "===> Install go.mod dependencies"
  - go mod tidy
  - chmod +x build.sh
  - sh build.sh